dist: trusty

language: java

addons:
  chrome: stable

jdk:
  openjdk8

before_script:
#  - chmod a+x gradlew
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew clean test