dist: trusty

language: java

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.gradle

jdk:
#  - oraclejdk8
  - openjdk11

before_install:
  - curl -s https://aerokube.com/cm/bash | bash && ./cm selenoid start --vnc --tmpfs 128

before_script:
#  - chmod a+x gradlew
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew clean test